name: CI (PRs and non-main)

on:
  push:
    branches:
      - feature/*

  pull_request:
    branches:
      - main
      - master
      - develop
      - feature/*

jobs:
  testing:
    uses: yankeeinlondon/gha/.github/workflows/test.yml@main
